### ISSUE TITLE
MTDEV and PROD- Link colors in map view different to those in 2D

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#737]
This is not related to the new map tiles, but noticed that links are dark blue and light blue in 2D view when you have epi and genetic, but in map view, it's displayed as green and light blue.
[Private Zenhub Image]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnBOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--626958a20e4d16db46c74401b3f389ea411a945a/MApLinkColors_DontMatch2D.JPG)

**Comment by mossy426-cdc** [comment]
This was interesting.  So it actually is still correct by displaying the appropriate blue. It's not "blue AND green" for the two origins.  If you do the origin tool tip for hovering over the link in the map view, it shows the origin is both.  So it should be overlayed/both blues, but the overlay implementation seems to only be in the 2d network view.  We'd have to port all that over to the map view and test.  WIll disucss in meeting

**Comment by mossy426-cdc** [comment]
As a note, this has been resolved for dev at the moment.  Prod soon after testing. 

I could not port over what was in the 2d network as the map view uses leaflet and it doesnt come with a "dashed" line in the library.  To work around this, I created new functionality that generates multiple lines and overlays them to accomplish the same effect.

**Comment by ikb6** [comment]
Still seeing green links, and not dashed lines. Can discuss

**Comment by ikb6** [comment]
reminder...this fix is not yet pushed to PROD-

**Comment by ikb6** [comment]
still seeing green links and blue links, not dashed. This is in ANGULAR as well as PROD. Perhaps you just added the old map version to Angular, and not the one where you added the fix?

**Comment by mossy426-cdc** [comment]
I've just made a push to the test angular url.  That still needed to be updaed.  As for prod I asked Reagan to check his latest deployment to ensure that it was pushed.
